variables:
  HUGO_VERSION: 0.147.7

default:
  image: ubuntu

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - set -eux pipefail
    - apt update && apt upgrade -y
    - apt install -y wget psutils nodejs npm # https://github.com/rrthomas/psutils
    - wget -O hugo.deb "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb"
    - dpkg -i hugo.deb
    - rm hugo.deb
    - npm install -g @vivliostyle/cli # https://github.com/vivliostyle/vivliostyle-cli?tab=readme-ov-file
    - npm install -g sass
    - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
    - cd exampleSite && hugo --gc --minify --baseURL "$CI_PAGES_URL/"
    - cd public && bash ./zineify.sh

  artifacts:
    paths:
      - exampleSite/public
    expire_in: 1 week

pages:
  stage: deploy
  environment: production
  script:
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - exampleSite/public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
