default:
  image: ubuntu

stages:
  - build
  # - deploy

build-job:
  stage: build
  script:
    - apt update && apt upgrade
    - apt install wget psutils nodejs # https://github.com/rrthomas/psutils
    - wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i hugo.deb && rm hugo.deb
    - npm install -g @vivliostyle/cli # https://github.com/vivliostyle/vivliostyle-cli?tab=readme-ov-file
    - "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
    - snap install dart-sass
    - cd exampleSite && hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"
    - cd public && bash ./zineify.sh

  artifacts:
    paths:
      - exampleSite/public
    expire_in: 1 week

# deploy-job:
#   stage: deploy
#   script:
#     - echo "Deploying to Staging"
#     - scp bin/hello remoteuser@remotehost:/remote/directory
#   rules:
#     - if: $CI_COMMIT_BRANCH == 'staging'